### PR TITLE
Added DecimalToOctal, and DecimalToRomanNumerals

### PR DESCRIPTION
**Pull request by Metropass**
Fixes Issues #252 and #264

### CODE REVIEW

**Comment by NarayanAdithya** [comment]
Hey how did you manage to get the lint check?

**Comment by lukew3** [comment]
> Hey how did you manage to get the lint check?

Google's [yapf formatter](https://github.com/google/yapf) should easily fix any lint issues you have. If issues still persist for some reason, just go to the checks tab of the pr and read the errors under the linter. It explains how to fix them. I recently formatted all current code in the repo so if there is an issue, it should be localized to your edits.

**Comment by Metropass** [comment]
@lukew3 Thank you much for fixing the conflict of the readme! 😄

**Comment by lukew3** [comment]
@Metropass No problem. Our readme is automatically generated so you don't need to edit it directly.

**Pull request merged**
