### PR TITLE
Data Summary Function

### PR DESCRIPTION
**Pull request by NarayanAdithya**
Returns a problem: containing list of numbers
                 solution: containing mean,std,variance

### CODE REVIEW

**Comment by lukew3** [comment]
Please remove pycache

**Comment by NarayanAdithya** [comment]
> Please remove pycache

Remove as in remove the pycache file itself?

**Comment by lukew3** [comment]
Remove the folder, the files will be removed with it.

**Comment by NarayanAdithya** [comment]
Hey what happened , i didnt understand the issue

**Comment by NarayanAdithya** [comment]
Just a doubt, why wasnt this added the hacktoberfest label?

**Pull request merged**
