### PR TITLE
Added Quotient of Powers with Same Base number

### PR DESCRIPTION
**Pull request by Nitsujed**
#267

### CODE REVIEW

**Comment by D-T-666** [comment]
could you use camelCase on the Generator?

**Comment by Nitsujed** [comment]
@D-T-666 Is that the naming convention used in this project? PEP8 doesnt dictate this convention (typically all lowercase, but can add _ if needed). I am happy to adjust if thats the convention for this project though...

**Comment by D-T-666** [comment]
image
Yeah it kind is the way it's been done.

**Comment by Nitsujed** [comment]
@D-T-666 Roger that. If thats the precedence, then sounds good. Might be helpful to create a style guide for the project if it is diverging from the PEP8 standards.

**Comment by helplessThor** [comment]
can anyone tell how to run these files for check? i am new to this platform

**Comment by Nitsujed** [comment]
#268 Added my other generator and changed to camelCase for this PR

**Comment by Nitsujed** [comment]
> can anyone tell how to run these files for check? i am new to this platform

@helplessThor 
I've just ran my own functions to test my own code. If you use the Python Console, you can 
- copy your function  and paste it into the console
- Then call the function to run `problem, solution = yourFunction()` 
- Then `print (problem,solution)`. 

Your print out should show the variable used in your formula and the ultimate solution. You can validate it works by running it a couple of times and checking the math.

**Pull request closed without merging**
