### PR TITLE
[urgent] Separated every function into a separate file under "funcs" folder.

### PR DESCRIPTION
**Pull request by D-T-666**
this needs to be merged before other merges or this will break

minor tweaks:
- removed HCF generator, it's the same as GCD but has a different name.
- had to adjust some whitespace, nothing major though.

importing works perfectly, makefile still gives bazillion warnings.

### CODE REVIEW

**Comment by D-T-666** [comment]
[](https://memegenerator.net/img/instances/66787035/please-please-approve-my-pull-request.jpg)

**Comment by D-T-666** [comment]
now what?

**Comment by lukew3** [comment]
I'm thinking that I'll merge it into the restructure branch and try to figure out how to add all the existing pull requests to it.

**Comment by D-T-666** [comment]
I'll try to help tomorrow if I can.

**Pull request merged**
