### PR TITLE
Added Compound Interest Problem Function

### PR DESCRIPTION
**Pull request by y0geshpatil**
Function to generate Compound Interest Problem.

### CODE REVIEW

**Comment by lukew3** [comment]
I'm getting some issues with merge conflicts. Can you remove changes to readme.md?

**Review by lukew3 — CHANGES_REQUESTED** [review]
Remove changes to README.md

**Comment by y0geshpatil** [comment]
Which changes?
Can please share details

**Comment by y0geshpatil** [comment]
> Remove changes to README.md



> Remove changes to README.md
Which changes?
Can please share details

**Pull request closed without merging**
