### PR TITLE
Compound Interest Added--- As per required changes

### PR DESCRIPTION
**Pull request by helplessThor**
As the changes were required, the new file has been added into function folder and init.py is also modified

### CODE REVIEW

**Comment by lukew3** [comment]
Please add generator class instance at bottom of mathgen.py

**Comment by helplessThor** [comment]
Okay I am adding

**Comment by helplessThor** [comment]
added the generator class

**Comment by lukew3** [comment]
Perfect, thanks and sorry for any trouble.

**Comment by helplessThor** [comment]
Thanks, ♥

**Pull request merged**
