### PR TITLE
Added Decimal to Binary generator

### PR DESCRIPTION
**Pull request by gokulp01**
I have added decimal to binary generator. If there are any discrepancies, do let me know :)

### CODE REVIEW

**Comment by lukew3** [comment]
@gokulp01 If you'd be interested we probably need a binary to decimal problem generator as well. I'll make an issue for it if you don't want it though.

**Comment by gokulp01** [comment]
@lukew3 sure, I'd be more than happy to take it up. Should I create a seperate issue for that? Or just a PR should do?

**Comment by lukew3** [comment]
Just a pr, thanks.

**Comment by gokulp01** [comment]
@lukew3  I've added it in #45 if there are any issues, do let me know :)

**Pull request merged**
