### PR TITLE
Adding pytest and tests GitHubAction

### PR DESCRIPTION
**Pull request by YuviGold**

### CODE REVIEW

**Comment by lukew3** [comment]
@YuviGold Thanks for adding this. Can you explain what it does? Obviously I'm new to maintaining open source and haven't learned this yet.

**Comment by lukew3** [comment]
I have experience with .gitignore but need help with the other stuff.

**Comment by YuviGold** [comment]
> @YuviGold Thanks for adding this. Can you explain what it does? Obviously I'm new to maintaining open source and haven't learned this yet.

@lukew3 This PR gives you an infrastructure for testing your code.
The tests are just running your functions, using `pytest `as a testing wrapper and `hypothesis `library for generating bunch of different inputs, while making sure the output stays valid.
I recommend this Youtube video - https://www.youtube.com/watch?v=MYucYon2-lk

The GitHub Action is just running the tests for every PR in order to make sure no one breaks the code.

**Comment by lukew3** [comment]
So everything happens in the background, right? You just go to the checks tab of the pull request to see if the tests passed I think.

**Comment by lukew3** [comment]
Thanks for the video recommendation, I'll watch it later tonight.

**Comment by YuviGold** [comment]
> So everything happens in the background, right? You just go to the checks tab of the pull request to see if the tests passed I think.

That's right. You can see it was added as part of your repository [Actions](https://github.com/Todarith/mathgenerator/actions?query=workflow%3A%22Run+tests%22).
You could also run it yourself with `pytest` or using the `Makefile` target with
```bash
make test
```

I'll extend the tests infrastructure later on.

**Comment by lukew3** [comment]
Thanks, I appreciate it.

**Pull request merged**
