### PR TITLE
 added magic squre generator function

### PR DESCRIPTION
**Pull request by vishnudk**
added magic squre generator function

### CODE REVIEW

**Comment by NarayanAdithya** [comment]
Hey do you knwo why the linter is failing?

**Comment by NarayanAdithya** [comment]
I am having same issue

**Comment by vishnudk** [comment]
i had a previous commit to the same repo but that worked without any issues

**Comment by vishnudk** [comment]
like i am new to git and how to update my forked repo with the changes in this main repo

**Comment by vishnudk** [comment]
i think the error  is due to the spacing in the code , there are some
rules for spacing in the code .

**Pull request closed without merging**
