### PR TITLE
Compound Interest Added

### PR DESCRIPTION
**Pull request by helplessThor**
Added Functionality of Compound Interest, in the main mathgen.py file

### CODE REVIEW

**Review by lukew3 — CHANGES_REQUESTED** [review]
Please modifiy your code to fit our new structure. Your function should go in a seperate file inside the funcs folder. Also add `from .compoundInterestFunc import *` at the bottom of the __init__.py file inside the funcs folder.

**Comment by helplessThor** [comment]
ok

**Comment by helplessThor** [comment]
but if you provide a hacktoberfest accepted, will be really helpful

**Comment by helplessThor** [comment]
despite forking, i am unable to get funcs folder in my repo, can you tell me how to fix it?

**Comment by helplessThor** [comment]
made the changes, and applied another pull request.

**Pull request closed without merging**
